### ISSUE TITLE
Should this work with redux-api-middleware?

### ISSUE THREAD

**Issue by hannupekka** [mathieudutour/redux-queue-offline#36]
Tried using this with https://www.npmjs.com/package/redux-api-middleware

Action:

```
{
  [CALL_API]: {
    endpoint: "http://www.example.com/api/users",
    method: "GET",
    types: [
      {
        type: "REQUEST",
        meta: {
          queueIfOffline: true
        }
      }, "SUCCESS", "FAILURE"
    ]
  }
}
```

When offline, action gets queued like it should but after connection restores, only `REQUEST` gets dispatched - no `SUCCESS` or `FAILURE`.

**Comment by mathieudutour** [comment]
Well because the action is queued, there is no `SUCCESS` or `FAILURE` actions ( which only happens when the `REQUEST` is dispatch), so that the intended behavior. Or am I missing something?
